name: Node setup and build
description: Checkout, setup Node, install dependencies and build Astro app

inputs:
  run-lint:
    description: "Whether to run lint before build"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run lint
      if: inputs.run-lint == 'true'
      run: npm run lint
      shell: bash

    - name: Build production
      run: npm run build
      shell: bash

